artifacts_root: artifacts

# here i am define data ingestion resources

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/krishnaik06/datasets/raw/main/winequality-data.zip
  local_data_file: artifacts/data_ingestion/data.zip # zip file downloaded this path
  unzip_dir: artifacts/data_ingestion # here download unzip file 


# here i am define data validation  resources

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt

# here i am define data transformation  resources
data_transformation:
  root_dir: artifacts/data_transformationd
  data_path: artifacts/data_ingestion/winequality-red.csv

# here i am define model trainer resources

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformationd/train.csv
  test_data_path: artifacts/data_transformationd/test.csv
  model_name: model.joblib


    